#!/bin/bash

# Description: A test script, same as blaze_farm.
while [ 0 -ne 1 ]; do
  xdotool keydown d &
  xdotool mousemove 683 388 click 1 &
  sleep 1.5 
  xdotool keyup d
  xdotool keydown a &
  xdotool mousemove 683 388 click 1 &
  sleep 1.5 
  xdotool keyup a
done
